### ISSUE TITLE
"Error: no such table: solar" with v1.5

### ISSUE THREAD

**Issue by AdeTheux** [katernet/darkmode#2] opened 2018-07-01 09:05 UTC
The script is in ~/Library/Application Support/Darkmode. Running it with "./darkmode.sh" from that directory returns "07/01/18 11:00:21 Error: no such table: solar" in the logs.
After that, a zero kb solar.db file has been created and darkmode has been turned on (but it's 11AM).

**Comment by katernet** [comment] 2018-07-07 02:27
Sorry for the late reply, Github didn't notify me of this new issue.

It seems your script is now in Application Support, which would break as it is looking for the script file path on first run - First note: https://github.com/katernet/darkmode/tree/bb2f6af7e4b1c1efb701c92c7a23103bfd25f6a3

Try version v1.6 which I just released, it explicity sets the script path in ~/Library/Application Support/darkmode/

**Comment by AdeTheux** [comment] 2018-07-07 08:48
Thanks. I didn't move it though. When I saw v1.5 changed drastically, I completely uninstalled v1.1 I had (following the steps you posted in another issue here).

Then I downloaded the .sh file to ~/Library/Application Support/Darkmode, ran ./darkmode.sh and then dark mode turned on (~10AM here).

Log file now states, in addition to _Error: no such table: solar_:
`07/07/18 10:44:02 ./darkmode.sh: line 36: [[: File Doesn't Exist, Will Create: /Users/Arnaud/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist: syntax error: invalid arithmetic operator (error token is "'t Exist, Will Create: /Users/Arnaud/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist")`

**Comment by katernet** [comment] 2018-07-07 10:55
Possibly your location isn't being picked up by the ipinfo.io/geo curl. Try hard code your location in the script - See note 1 in README

The error mentioning line 36 has been fixed in release v1.6 - Stopped uninstall function from querying the launch agents, which wouldn't exist after uninstall.

**Comment by AdeTheux** [comment] 2018-07-07 13:58
I must've failed miserably when uninstalling the previous version. I tried again, uninstalled everything, rebooted, re-installed and the solar.db file got updated with results!
Thanks

**Comment by katernet** [comment] 2018-07-07 15:23
Awesome! Thanks @AdeTheux

**Comment by AdeTheux** [comment] 2018-09-26 07:38
I've just upgraded to Mojave and the same issue happened again. After rebooting once the upgrade was completed, dark mode was turned on automatically (it's 9:30AM here).
So I checked the log, and there are a few lines with today's date:
`Error. no such table: solar`

The solar.db file is also an empty file (zero kb) 🤔 

Any thoughts or ideas of what I could do to get the script working again?
Thanks

**Comment by katernet** [comment] 2018-09-26 11:16
Hi @AdeTheux lets revisit my previous theory. If the solar table is empty, then it is still being created in the solar function, however empty values are possibly being stored. The values are variables received by the curl commands. 

Try these commands. Does the first output your country code and the next output a time? The first queries your country from ipinfo.io and the second queries the sunrise time from an example location in the Yahoo Weather API.

```
curl -s ipinfo.io/geo | awk -F: '{print $2}' | awk 'FNR ==5 {print}' | sed 's/[", ]//g'"
curl -s "https://query.yahooapis.com/v1/public/yql?q=select%20astronomy.sunset%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22maui%2C%20hi%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys" | awk -F\" '{print $22}'
```

**Comment by AdeTheux** [comment] 2018-09-26 13:11
Hi @katernet , thanks again for taking the time to help me with this. Both curl commands work and return the correct value: country code CH for Switzerland, and the sunset time of 6:18pm looks alight.

**Comment by katernet** [comment] 2018-09-26 13:54
Tough one! I see that you have upgraded to Mojave and so the script would have already been installed after upgrading. I do know that there are new security features in Mojave that prompt you to allow access to System Events when first running the script (see first note in [README](https://github.com/katernet/darkmode/blob/master/README.md))

And so can you please try an uninstall (again I know 😝) 

`$ ./darkmode.sh /u`

and download and run the latest release and accept these security prompts? See how that goes. At least then we can start fresh again.

I fresh installed the Mojave release on my other Mac and ran darkmode and it worked fine.

**Comment by AdeTheux** [comment] 2018-09-26 15:41
OK so I uninstalled, rebooted, downloaded, and ran the script. All the files are back in place, the solar.db file is about 12KB so that's a good start… but no time data was stored 😳
`26/09/18 17:22:34 darkmode: Solar query stored - Sunrise:  Sunset:`

The plist files therefore don't contain any time, just 0:0. And FYI just after running the script, dark mode was activated even though it was the middle of the afternoon (but I guess it's the logic of the script?)
Thanks.

**Comment by bandgeekdante** [comment] 2018-09-26 20:21
I had a related issue earlier. For me it happens when the solar query runs when my laptop isn't connected to the internet; it seems to store zero values for the sunrise/sunset times which causes strange behaviour in when it is dark or light. Would it be possible for the script to detect whether it's actually able to connect to the API and try again the next day or something like that if it doesn't connect?

**Comment by katernet** [comment] 2018-09-26 22:00
@bandgeekdante great point, I hadn't thought about the internet connection. My main rig is over ethernet and in my testing I never encountered this issue.

I was able to replicate this on my MacBook running the script fresh with Wifi turned off, the script ran instantly the first time (normally takes a couple of seconds due to the curl commands) and the log showed no solar times, 0s showed in the launch agent plist and dark mode turned on after sunrise.

@AdeTheux are you using a MacBook or were you over Wifi when you last ran the script? Possibly it never connected to ipinfo and the weather API when you last ran it.

I can certainly incorporate a connection check into the next release. Something like this which waits either 20s or a successful connection to the API

```bash
time=$(date +%s)
while true && [ $(( $(date +%s) - 20)) -lt $time ]; do
	if curl -s query.yahooapis.com; then
		break
	fi
done
```

**Comment by AdeTheux** [comment] 2018-09-27 07:31
@katernet I'm using a MacBook Pro, always on WiFi. Note that it didn't store 0 in the .db file, it filled it with no number at all.

**Comment by katernet** [comment] 2018-09-27 13:01
I can confirm that running darkmode with no internet connection stores empty vaults in the db. And as per my previous reply I was able to replicate 0's in the launch agent plist and no times appearing in the log. This is either a network issue on your end or I'm not sure on what else can resolve this, unless I can think of something later or someone else chimes in with an idea. Sorry!

The best I can do at this point in time is update the script with a connection checker that exits after 20s of no connection to the API, which I have now released in [1.7.2](https://github.com/katernet/darkmode/releases/tag/1.7.2)

**Comment by AdeTheux** [comment] 2018-09-27 13:38
Thanks, I'll update to 1.7.2 and try to test this a bit more.

**Comment by AdeTheux** [comment] 2018-09-27 13:45
Just FYI there was a slight change compared to before with 1.7.2: I now had two popups asking me to grant authorisation to system events to make changes (or something similar like you mentioned before).
Still stored 0, but I didn't have the popup before this version.

**Comment by katernet** [comment] 2018-09-27 14:08
That is a new security in Mojave which appears when the AppleScript runs. I added this to the readme when I was testing the dev betas.

**Comment by katernet** [comment] 2018-09-28 09:16
@AdeTheux check out Issue #7 and the new release [1.8](https://github.com/katernet/darkmode/releases/tag/1.8) now using Night Shift for the solar times instead of the Yahoo API. Hopefully this works better for you.

**Comment by AdeTheux** [comment] 2018-09-28 09:31
Awesome, thank you! I'll give it a go and report back.

EDIT: I'll wait and see how it behaves tonight, but this is already looking better 🙂
`28/09/18 11:33:36 darkmode: Solar query stored - Sunrise: 07:32 Sunset: 19:11`

**Comment by katernet** [comment] 2018-09-28 09:50
Woohoo! Looks good let me know if there are any further issues.

**Comment by bandgeekdante** [comment] 2018-09-29 01:20
Oh no... I upgraded to 1.8 and now I'm getting the "no such table: solar" error :(
Update: Looks like I was able to fix it. It seems the uninstaller didn't delete the darkmode folder inside of Application Support for some reason; when I manually deleted that then reinstalled 1.8 everything worked properly.

**Comment by katernet** [comment] 2018-09-29 03:12
😮 

I'm glad that you were able to fix it. Yes if the darkmode folder already exists then the solar function won't run until a Monday and so it would not set solar values.

I've also experienced the darkmode folder still existing after an uninstall when trying to replicate bugs. I'll look into why it isn't getting moved to the trash.

EDIT: It's because the uninstall function is trying to move the darkmode folder to the trash when there is already a folder in there with the same name. I will include a fix in the next commit.

**Comment by bandgeekdante** [comment] 2018-10-01 16:30
So it's now working almost perfectly, but I got a different database-related issue showing up in my log today:
10/01/18 08:18:37 Error: near line 3: database is locked
01/10/18 08:18:37 darkmode: Solar query stored - Sunrise: 07:41 Sunset: 19:12
01/10/18 08:18:37 darkmode: Solar query stored - Sunrise: 07:41 Sunset: 19:12
10/01/18 08:18:37 Error: near line 4: database is locked
The script at the time ran when I unplugged my laptop which woke it, but had not unlocked my account yet. I suspect that because my files are encrypted the script might not be able to edit files until I unlock it? Also I'm not sure why it appears that it ran twice but that doesn't bother me.

**Comment by katernet** [comment] 2018-10-02 04:58
I suspect that the database was encrypted due to Filevault and not decrypted until after login. However, I thought that launchagents (which darkmode uses) only run after the user has logged in. Thanks for letting me know that your files were encrypted, if you hadn't mentioned that I would have had no idea! :laughing: 

Possibly the launchagent is running the script quick enough that your files hadn't been decrypted yet after entering your password?

I'll enable Filevault on my Mojave partition and do some testing later on today.

Can you run the following command. On my machine LimitSessionToType is set to Aqua, which I originally thought could be a fix, until I found launchd already seems to set this.

`$ launchctl list io.github.katernet.darkmode.sunrise `

As for why the script ran twice, Possibly the script is running twice due to the first failure, or this is to do with the RunAtLoad key which I added to set the script to run on login after startup from shutdown (missed schedule only works on wake from sleep)

**Comment by bandgeekdante** [comment] 2018-10-02 16:04
I get this:
{
	"LimitLoadToSessionType" = "Aqua";
	"Label" = "io.github.katernet.darkmode.sunrise";
	"TimeOut" = 30;
	"OnDemand" = true;
	"LastExitStatus" = 0;
	"Program" = "/Users/Dr_B/Library/Application Support/darkmode/darkmode.sh";
};
Also after posting that comment (at sunset) I got another security prompt from macOS; perhaps saying yes to that fixed it?

**Comment by katernet** [comment] 2018-10-02 21:50
I did some testing by enabling FileVault and shutting down. Booted up after sunrise and didn't type my login password for a minute, logged in and Dark Mode was turned off ok. Unable to replicate your `database is locked` issue.

That's good that the security prompt showed, in my testing in Mojave betas there was a security prompt for Terminal when you first ran the script and then a second prompt showed for 'darkmode.sh' when the script next ran on launchd schedule. This showed Terminal and darkmode.sh in Security system preferences > Privacy > Automation.

However, in the release I noticed for me the second security prompt hasn't showed and Terminal is the only one showing in Automation. Do you know if the security prompt was for darkmode.sh? Is the script showing in Automation security preferences?

**Comment by bandgeekdante** [comment] 2018-10-02 22:42
Hi katernet, I don't remember exactly what the security prompt asked for. It looks like the only relevant thing in the Automation security preferences is Terminal having access to System Events.app. I don't see darkmode.sh specifically in the list. Still I suspect that the last security prompt did fix the issue but I'll let you know if that's not the case

**Comment by katernet** [comment] 2018-10-03 11:17
Thanks @bandgeekdante yes please keep me updated if you have any further issues.

**Comment by bandgeekdante** [comment] 2018-10-03 16:06
No problem! By the way since you've been so awesome with this is there a way I could send you a donation?

**Comment by katernet** [comment] 2018-10-03 21:21
Thanks @bandgeekdante you were actually pretty awesome too in helping out with @AdeTheux's issue. No donation required, I'm just happy to share my ideas.

**Comment by katernet** [comment] 2018-10-06 04:01
How's it going so far @bandgeekdante ? Are you getting any more error logs for `Error: no such table: solar`?

**Comment by bandgeekdante** [comment] 2018-10-06 04:20
@katernet Everything's looking good from my end. Are you sure you don't want a donation btw?

**Comment by katernet** [comment] 2018-10-06 04:43
Nope 😄 
Closing this issue off then. Thanks.

**Closed as completed by katernet** 2018-10-06 04:43 UTC
Labels: bug
