### ISSUE TITLE
New install, log shows ":StartCalendarInterval:Minute" Entry Already Exists

### ISSUE THREAD

**Issue by etrahretep** [katernet/darkmode#11] opened 2018-10-05 12:06 UTC
When uninstalling and reinstalling my logo shows:

05/10/18 14:03:35 darkmode: Solar query stored - Sunrise: 07:53 Sunset: 18:57
10/05/18 14:03:36 /Users/peter/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist: Could not find specified service
10/05/18 14:03:36 Add: ":StartCalendarInterval:Hour" Entry Already Exists
10/05/18 14:03:36 Add: ":StartCalendarInterval:Minute" Entry Already Exists

any idea?

**Comment by katernet** [comment] 2018-10-05 13:29
Hi @etrahretep thanks for reporting the issue. 

Which version of darkmode are you using and what is the output of this?

`launchctl list | grep katernet`

Uninstall using `./darkmode.sh /u` and make sure the following files/folders are removed and the launch agents are not loaded by running the first command again.
~/Library/Application\ Support/darkmode
~/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist
~/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist

Then run darkmode again and let me know if there are more errors in the log. Make sure to use the latest release 1.8 if you are not.

**Comment by etrahretep** [comment] 2018-10-05 15:39
Last login: Fri Oct  5 14:34:33 on ttys000
Peters-MBP:~ peter$ launchctl list | grep katernet
-	0	io.github.katernet.darkmode.sunrise
-	0	io.github.katernet.darkmode.sunset
Peters-MBP:~ peter$ 

Uninstalled several time with the same log...

05/10/18 17:39:00 darkmode: Solar query stored - Sunrise: 07:53 Sunset: 18:55
10/05/18 17:39:01 /Users/peter/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist: Could not find specified service
10/05/18 17:39:01 Add: ":StartCalendarInterval:Hour" Entry Already Exists
10/05/18 17:39:01 Add: ":StartCalendarInterval:Minute" Entry Already Exists

**Comment by katernet** [comment] 2018-10-06 03:38
I've done some testing and was able to replicate your log once, except for the `StartCalendarInterval:Minute` entry, and I was unable to find the cause. Subsequent testing does not replicate the results.

It seems when I did get the errors that it was functioning ok. Is your script functioning ok (apart from the error logs)? And are you using the latest release version 1.8?

**Comment by etrahretep** [comment] 2018-10-06 06:52
It's running on 2 machines of which one has the error log. It's is working though. Using 1.8
Did some further testing but the error persists.
Other question. How simple is it to change the script to pull the times every day instead of once a week?

**Comment by katernet** [comment] 2018-10-06 08:12
Weird. I've got the error once and only one of your macs gets the error. I'll keep looking into it.

Very easy, in the `darkMode()` function change the following from

```bash
if [ "$(date +%u)" = 1 ]; then
	solar
fi
```

to just 

```bash
solar
```

**Comment by katernet** [comment] 2018-10-06 08:14
What model and year (in About this Mac) are the Mac models which have the issue and don't have the issue?

**Comment by etrahretep** [comment] 2018-10-06 08:27
A 2017 MBP and a 2012 iMac. But I believe It's not machine dependent. Having issues on the MBP but when starting from iMac backup on MBP no issues... (same system setup)
Don't bother investigating; I reinstalled iMac backup to MBA. All running smoothly now.
Thanks very much for your help!

**Comment by katernet** [comment] 2018-10-06 08:50
Thanks glad you got it sorted. Closing this one off now.

**Closed as completed by katernet** 2018-10-06 08:50 UTC
Labels: bug
