### ISSUE TITLE
Illegal time format

### ISSUE THREAD

**Issue by AdeTheux** [katernet/darkmode#10] opened 2018-10-02 09:27 UTC
Just posting this as a heads up: I saw this yesterday in the logs:

`10/01/18 18:12:45 Failed conversion of ``'' using format ``%Y-%m-%d %H:%M:%S %z''
10/01/18 18:12:45 date: illegal time format
10/01/18 18:12:45 usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
01/10/18 18:12:45 darkmode: Solar query stored - Sunrise:  Sunset: 
10/01/18 18:12:45             [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]`

The script seems to still be running fine though.
Would it be related to the time format difference between US and where I am (Europe)?

**Comment by katernet** [comment] 2018-10-02 10:14
The date command is not getting time values, as indicated by the empty quotes `''`

What is the output of the below command? 

`$ /usr/bin/corebrightnessdiag nightshift-internal | grep nextSunrise | cut -d \" -f2`

**Comment by AdeTheux** [comment] 2018-10-02 10:15
2018-10-03 05:37:57 +0000

**Comment by katernet** [comment] 2018-10-02 10:31
Hmm that isn't an empty output, which is what your log was saying. I'll look into it.

**Comment by AdeTheux** [comment] 2018-10-02 10:38
Thanks. I'll also check again later or tomorrow if there's a new line like that in the log. All the rest is now looking good since the switch to night shift.

**Comment by katernet** [comment] 2018-10-02 21:52
Thanks @AdeTheux let me know if any further issues. I'm currently looking into bugs into the new version, I've had a few bug reports here and on Reddit.

**Comment by AdeTheux** [comment] 2018-10-03 07:07
FYI, no new log line about this issue this morning.

**Comment by katernet** [comment] 2018-10-03 11:19
Thanks @AdeTheux strange that there were no values provided to the date command and now it is fine, I guess that is good news. Please let me know if it happens again.

**Comment by katernet** [comment] 2018-10-06 03:59
How's it going so far @AdeTheux ?

**Comment by krema** [comment] 2018-10-07 10:43
I had the same issue in Mojave and found the solution by myself.

You need to make sure that you have allowed the privacy & security settings to allow the location services to get information about your timezone and system settings.

**Comment by katernet** [comment] 2018-10-07 11:59
Nice info @krema you are correct, I did encounter this in my testing. You need to have Setting Timezone enabled in System Preferences > Security > Location Services > System Services > Details for Night Shift to work and to allow sunrise/sunset times to be queried from Night Shift. This is enabled by default. I'll put this in the Readme.

Without this enabled the output to darkmode's commands querying Night Shift will be null and cause the logs as per the OP.

It seems @AdeTheux did originally get null figures, however when he ran the commands manually as above, he got an output. So this could or could not be related.

**Comment by AdeTheux** [comment] 2018-10-08 07:56
> How's it going so far @AdeTheux ?

I don't have the 'illegal time format' error in the log file anymore, but this one now appeared and dark mode is not turned off automatically in the morning. Do you want me to open another issue, or uninstall/reinstall?
`10/06/18 16:57:26 /Users/Arnaud/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist: Could not find specified service`

**Comment by katernet** [comment] 2018-10-08 13:21
An uninstall/reinstall will probably fix it, but I don't like how this is becoming a common fix method.

This error and a schedule not working usually means an launch agent isn't running properly. I'll have a look into it.

What is the output of `launchctl list | grep katernet`

**Comment by AdeTheux** [comment] 2018-10-08 15:04
I'll try an uninstall/reinstall now.
This is the output of the command:
`114:-	0	io.github.katernet.darkmode.sunrise
257:-	0	io.github.katernet.darkmode.sunset`

**Comment by AdeTheux** [comment] 2018-10-09 06:21
Uninstall/reinstall seemed to have fixed it.

**Comment by katernet** [comment] 2018-10-09 07:52
Thanks that's good. Yeah I don't want to have people regularly having uninstall and reinstall to get it working again. I'll be doing some testing and look into it. I did make a change in 1.8.1 to hopefully prevent the script from messing up after multiple uninstalls.

**Comment by axelra82** [comment] 2018-10-11 12:45
Moving over here from [issue#10](https://github.com/katernet/darkmode/issues/12).
I ran all the requested lines in terminal (after downloading the latest version, 1.8.1 and first uninstalling whatever version I had before installing latest download again)
- - - -
```
launchctl list | grep katernet
respons -> -	0	io.github.katernet.darkmode.sunrise
respons -> -	0	io.github.katernet.darkmode.sunset

/usr/libexec/PlistBuddy -c "Print :StartCalendarInterval:Hour" ~/Library/LaunchAgents/io.github.katernet.darkmode.sunrise.plist
respons -> 0

sqlite3 ~/Library/Application\ Support/darkmode/solar.db 'SELECT time FROM solar WHERE id=1;' "" 
respons -> 
```
(last one was empty)
- - - -

When I installed it now (during daytime) it switched to dark mode (don't know if that is correct or not, but just thought I should mention it for bug tracking purposes).
I'll check again tomorrow morning to see if this resolved the issue.

**PS.** You can close the previous issue. I was not aware of this one. I'll post any further comments here 😄

**Comment by katernet** [comment] 2018-10-11 13:03
@axelra82 can you please post the contents of the log file?

**Comment by axelra82** [comment] 2018-10-11 13:12
**My bad!** Missed that. Here you go:
```
10/11/18 14:36:23 Failed conversion of ``'' using format ``%Y-%m-%d %H:%M:%S %z''
10/11/18 14:36:23 date: illegal time format
10/11/18 14:36:23 usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
10/11/18 14:36:23             [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
10/11/18 14:36:23 Failed conversion of ``'' using format ``%Y-%m-%d %H:%M:%S %z''
10/11/18 14:36:23 date: illegal time format
10/11/18 14:36:23 usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
11/10/18 14:36:23 darkmode: Solar query stored - Sunrise:  Sunset: 
10/11/18 14:36:23             [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```

**Comment by katernet** [comment] 2018-10-11 20:39
Ok so you are still getting empty times for the sunrise/sunset dates in the Night Shift commands even after reinstalling.

Can you please make sure that Timezone location settings are enabled in the Security settings - instructions in the README notes.

**Comment by katernet** [comment] 2018-10-11 20:41
If Timezone is already enabled, what is the output of this one command?

`$ riseT=$(/usr/bin/corebrightnessdiag nightshift-internal | grep nextSunrise | cut -d \" -f2); date -jf "%Y-%m-%d %H:%M:%S %z" "$riseT" +"%H:%M"`

**Comment by krema** [comment] 2018-10-12 04:36
@katernet Wouldn't it be good to check the security settings before installing and informing the user that he has to enable it by himself before he can continue the installation? Or is there a way to trigger the security settings popup from the system?

**Comment by axelra82** [comment] 2018-10-12 09:36
@katernet here is the command with the response
```
riseT=$(/usr/bin/corebrightnessdiag nightshift-internal | grep nextSunrise | cut -d \" -f2); date -jf "%Y-%m-%d %H:%M:%S %z" "$riseT" +"%H:%M"
response -> 07:26
```
I also notised last night while working that it switched to dark mode at midnight (12.00 AM), which is long after sunset here (Sweden) this time of year.

**Comment by katernet** [comment] 2018-10-12 10:48
@krema That would be a good idea. I'll look into it. From initial research, I cannot yet find a defaults command or database file which houses this setting that I can check.

@axelra82 As per my previous [reply](https://github.com/katernet/darkmode/issues/10#issuecomment-429110408) is Timezone enabled in Security settings? (see README for instructions)

The script is getting null values from the Night Shift commands, this is storing zeros in the launchd plists which is causing the script to run at midnight.

**Comment by axelra82** [comment] 2018-10-12 12:28
@katernet Sorry, yes, Timezone is enabled (and was enabled before installing).

**Comment by cesarradtke** [comment] 2018-10-12 16:46
> @katernet here is the command with the response
> 
> ```
> riseT=$(/usr/bin/corebrightnessdiag nightshift-internal | grep nextSunrise | cut -d \" -f2); date -jf "%Y-%m-%d %H:%M:%S %z" "$riseT" +"%H:%M"
> response -> 07:26
> ```
> I also notised last night while working that it switched to dark mode at midnight (12.00 AM), which is long after sunset here (Sweden) this time of year.

my response is...

Failed conversion of ``2018-10-14 8:57:19 AM +0000'' using format ``%Y-%m-%d %H:%M:%S %z''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

**Comment by katernet** [comment] 2018-10-13 01:45
@axelra82 Hi Axel I still haven't found your issue. Can you please download the following test script and run it twice and then send the contents of the logs to katernet -at- protonmail.com

For the first run, enter an Hour and Minute time in 24H format between sunrise and sunset time, 
and then the second run enter a time after sunset and before sunrise.

Make sure to copy the contents of the log after the first run, as the log is cleared each time.

[darkmodetest.sh.zip](https://github.com/katernet/darkmode/blob/beta/darkmodetest.sh.zip) - Click the "Download" button

You can delete all the files the script created on your desktop once done.

@cesarradtke it seems your time output from the Night Shift time includes "AM" and it is causing the time convert to fail. Every one else's I've seen is in 24H time. I've done some research and can't work out how to force it to 24H time.

Try setting your clock to 24H time and your Time Format to 24H time in Language and Region in System Preferences and then post the output of that command again.

**Comment by axelra82** [comment] 2018-10-13 12:58
Sure, will do. Tried running it, e.g. with 14:48, 14.48, 14 48 and 1448.
The last one (with no dot, space or colon, returns
`Time out of bounds. Exiting.`
every other entry returns an error before ☝️
`syntax error: invalid arithmetic operator`

So the time format I should enter is HHmm? Also, did you mean for me to enter the current time, at any point between sunrise and sunset, i.e. during the day and then once more during the night?
Just wanted to make sure I get it right  😄

**Comment by katernet** [comment] 2018-10-13 14:15
No you enter hours and then minutes. Example:

```
$ ./darkmodetest.sh
Enter current Hour time in 24H format: 07
Enter current Min time: 30
```

Yes run a time between sunrise and sunset and get log contents. Then run a time between sunset and sunrise (the next day) and get log contents.

**Comment by axelra82** [comment] 2018-10-13 18:04
Got it! Done once after sunset now. Will do next after sunrise tomorrow and send you the log files.

**Comment by katernet** [comment] 2018-10-13 22:47
You don't need to wait for the next sunrise. Run it with Hr and Min values once and then again straight afterwards as I described. Sorry if I was not clear enough.

The test script does not do anything, it just runs the framework of the script and all I want to see is the set -x output.

**Comment by querkmachine** [comment] 2018-10-15 14:53
Don't know if it's related to this specifically, but all of today the script has been pinging me into dark mode. I did a bit of digging and found the Yahoo API that determines the sunset time is returning a malformed time ("6:6 pm"). 

`{"query":{"count":1,"created":"2018-10-15T14:42:43Z","lang":"en-gb","results":{"channel":{"astronomy":{"sunset":"6:6 pm"}}}}}`

This is the the result of directly `curl`ing the URL in the code, before the script has manipulated anything, so would seem to be a snafu on Yahoo's side?

**Comment by katernet** [comment] 2018-10-15 20:45
I changed the solar time "engine" of darkmode from the Yahoo weather API to Night Shift in v1.8 and this issue relates to some users getting null time values in 1.8 and the associated date command errors. If your Mac supports Night Shift I would recommend updating. If not then please make a new issue.

I did a quick test with my code in [v1.7.2](https://github.com/katernet/darkmode/blob/5cbe4dedd1ccb9b5fad953efb0092940f4effb48/Darkmode.sh) (line 91-94) and if the sunset time retrieved from the Yahoo API is "6:6 pm" then darkmode will have no problem, as the time is converted to 24H and launchd uses single digits for times <10 anyway.

```bash
$ setT="6:6 pm"
$ date -jf "%I:%M %p" "${setT}" +"%H:%M"
```

Result is 18:06

**Comment by axelra82** [comment] 2018-10-15 20:54
@katernet sorry for the delay. I've run the test script now and emailed you the logs.

**Comment by katernet** [comment] 2018-10-15 20:59
Thanks. I'll take a look when I am back from work.

**Comment by querkmachine** [comment] 2018-10-15 21:00
@katernet Fair enough, I've got no explanation for why darkmode was bugging out for me today then. I've upgraded to 1.8.1 now.

**Comment by cesarradtke** [comment] 2019-01-10 19:16
Think I found problem. I don't know if always displays like that, but in my case, "corebrightnessdiag nightshift-internal"  returned date-time in 12 hour format, including AM/PM word. So, riseTL and setTL variable will store wrong value. Well, I added a test and '%p'  to solve.
[patch.diff.txt](https://github.com/katernet/darkmode/files/2746752/patch.diff.txt)

**Comment by katernet** [comment] 2019-01-11 07:38
@cesarradtke Great nice work! I never picked up on this as I set my system to 24H, however most users will have the default 12H. 

Can you please create a pull request?

This will resolve your issue below, however it may not resolve the OP, although hopefully it does!

> Failed conversion of `2018-10-14 8:57:19 AM +0000'' using format `%Y-%m-%d %H:%M:%S %z''
> date: illegal time format
> usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
> [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

Also digging your FreeBSD avatar!

**Comment by katernet** [comment] 2019-01-13 06:58
Committed @cesarradtke's pull request and published release 1.8.2

**Comment by katernet** [comment] 2019-01-13 06:59
I've been quiet on this issue in the past few months, as to be honest I don't know how to fix it. I reviewed @axelra82's test script logs and looked over the master script and did some testing over the holidays.

I'll keep this issue open, anyone is free to share any ideas.

**Comment by one8loop** [comment] 2019-01-28 17:06
Hi @katernet, I have an idea about the 'Illegal time format' bug.
The privacy setting you mentioned above is not sufficient to enable localization on macOS. WiFi should be enabled too. When I use an Ethernet connection, even Night Shift does not work till WiFi is turned on.

This is the output of `corebrightnessdiag nightshift-internal` when I'm using a wired connection and WiFi is disabled:
```
Night Shift Sunset/Sunrise
(null) 
```
Then, as soon as I turn on WiFi, the same command returns the proper data:
```
Night Shift Sunset/Sunrise
{
    isDaylight = 0;
    nextSunrise = "2019-01-30 06:52:23 +0000";
    nextSunset = "2019-01-29 16:18:03 +0000";
    previousSunrise = "2019-01-28 06:54:36 +0000";
    previousSunset = "2019-01-27 16:15:06 +0000";
    sunrise = "2019-01-29 06:53:30 +0000";
    sunset = "2019-01-28 16:16:34 +0000";
} 
```
It seems that macOS is using the same localisation framework as iOS which relies on neighbouring wifi networks.

You can reproduce this behaviour by restarting your Mac before sunset and with WiFi disabled. After login your script will rise the error and, moreover, when sunset occurs Night Shift will stay disabled.

I really enjoy your script, thanks for sharing it with all of us!!
I hope I was helpful.

**Comment by katernet** [comment] 2019-01-31 12:17
@one8loop great good work! I was able to replicate this by turning off wifi and then rebooting (nightshift command would still output with wifi off and without rebooting).

I'll update the ReadMe shortly.

@AdeTheux / others are you please able to test this?

**Comment by bandgeekdante** [comment] 2019-04-04 17:23
@katernet Could there be a way to delay running the Night Shift check until Wifi is connected? I usually use Wifi but sometimes it takes a few seconds to connect and the script usually runs in those few seconds, triggering the bug
Edit: I wrapped the "solar" function in an if block which tests for internet connectivity (not strictly Wifi, but that's the only type of connection I ever use so for me it's no problem). I'll see if this fixes the issue

**Comment by katernet** [comment] 2019-04-25 10:20
Hi @bandgeekdante sorry for the late reply. I've updated the beta branch with a Wifi check that exits the script if wifi is not connected after 30 seconds. I've also added a DST checker and replied to the other issue.

```bash
t=0
while [[ "$wStatus" != "running" ]]; do
	t=$((t+1))
	wStatus=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | sed -n 5p | awk '{print $2}')
	sleep 1
	if [ $t -eq 30 ]; then
		echo "darkmode: Wifi connection timeout." >&2
		exit 1
	fi
done
```

Can you please test and let me know here if there are any issues. Just replace the script ~/Library/Application Support/darkmode.sh with the beta script.

**Comment by katernet** [comment] 2019-07-05 11:35
As pointed out by @bandgeekdante the issue was related to the Night Shift command requiring to pull sunset data while on wifi.

I have released [2.0](https://github.com/katernet/darkmode/releases/tag/2.0) which has a wifi checker and exits if not connected to wifi.

If this issue occurs again, please comment and I will reopen this issue.

**Comment by bandgeekdante** [comment] 2019-09-11 13:44
Hi Katernet, unfortunately I'm getting the issue again, running version 2.0:
`09/09/19 08:51:46 darkmode: Failed conversion of ``'' using format ``%Y-%m-%d %H:%M:%S %z''
09/09/19 08:51:46 darkmode: date: illegal time format
09/09/19 08:51:46 darkmode: usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
09/09/19 08:51:46 darkmode:             [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
09/09/19 08:51:46 darkmode: Failed conversion of ``'' using format ``%Y-%m-%d %H:%M:%S %z''
09/09/19 08:51:46 darkmode: date: illegal time format
09/09/19 08:51:46 darkmode: usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
09/09/19 08:51:46 darkmode:             [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
09/09/19 08:51:46 darkmode: Solar query stored - Sunrise:  Sunset: `

**Comment by katernet** [comment] 2019-09-13 08:50
Hi @bandgeekdante sorry about that. I thought that the changes in 2.0 would resolve this!

So we now know the issue is caused by `corebrightnessdiag nightshift-internal` outputting null solar values to the script.

I see that you are on wifi. Run the above command and report the results, it's either going to be null or output values (will probably have values, knowing the finickiness of this)

If it's null and you are connected to wifi, do a reboot and then run the command again and report the results.

If it has values, we can see from your log this occurred on a Monday, which is when the `solar` function runs that exectutes `corebrightnessdiag`. In the script there is a Wifi checker which exits the script if not connected to wifi before running `solar`, so we know the code is detecting your wifi is 'running' and then executing `solar`. 

So then basically the issue is `corebrightnessdiag` reporting null values when you are connected to wifi. As @one8loop pointed out the reason for the null values is not having a wifi connection, and I was able to replicate this. And so I really don't know, this looks like it's going into Apple bug territory, where their built in binary is not reporting any data, when the conditions are met. 

Again try a reboot. Then run the script manually again with 
`$ ~/Library/Application\ Support/darkmode/darkmode.sh` 

EDIT: This only runs on a Monday. You can change the condition on [line 37](https://github.com/katernet/darkmode/blob/master/darkmode.sh#L37) to the following to run solar any day.

```bash
if [ "$(date +%u)" -gt 0 ]; then
```

and check the log to see if the error shows again. If not then your darkmode script will continue to run with a solar schedule.

If no luck, all I can think of is increasing the wifi checker timeout in seconds on [line 218](https://github.com/katernet/darkmode/blob/master/darkmode.sh#L218)

```bash
if [ $t -eq 30 ]; then
```

Change to 60 or even 120 - don't worry your system won't slow down, the darkmode script will just stay open in a bash invocation for a bit longer. Maybe your system doesn't report on localization data for a bit longer after a startup/resume from sleep.

You can test this by booting up/resuming from sleep and straight away run `$ corebrightnessdiag nightshift-internal` after your wifi connects and seeing how long it takes to report values correctly. If it's straight away after a wifi connection, then increasing the timeout won't have any effect. The issue then leads back to Apple's binary being buggy on your system again.

**Comment by katernet** [comment] 2019-09-13 09:09
You also could try downgrading to 1.7.2 which uses Yahoo weather API 😛 and see how that goes?
This will be slower to gather solar data, but you won't notice it if you're not monitoring the script.

If all else fails, you could just set your own static times, if you're happy with that. Uninstall darkmode and run with 24H time arguments for sunrise and sunset.

e.g. 
`$ darkmode.sh 0600 1900`

**Comment by bandgeekdante** [comment] 2019-09-16 15:06
Hi katernet, I tried uninstalling and reinstalling, and the same bug happened again. When I run the above command, I get (null) for sunrise/sunset for quite a long time after connecting to Wifi. I'll try changing the timeout to 120 to see if the problem gets fixed...

**Comment by katernet** [comment] 2019-09-17 08:01
I see, it seems there's something wrong with the corebrightnessdiag binary on your Mac or your wifi's localization queries, which fall out of my scope.

See how increasing the timeout goes, else try the other alternatives I suggested.

Let me know how it goes.

**Comment by katernet** [comment] 2019-10-01 09:17
How's it going @bandgeekdante ?

**Comment by bandgeekdante** [comment] 2019-10-01 13:40
So far so good!

**Comment by katernet** [comment] 2019-10-01 22:53
Cool! If you need any more help let me know. If the issue is resolved, feel free to close this out.

**Comment by katernet** [comment] 2019-10-10 11:00
@bandgeekdante if the issue crops up again, try removing the `log()` function and the line `exec 2> >(log)` just underneath.

I've been doing some testing and found when first running the script, the sqlite statements in `getTime` still run when isolated out with an if condition, causing `Error: no such table: solar` to show 4 times in the log.

When I turn the logging off these errors do not show in the console. I still haven't worked out why it occurs (copypasted the log function from somewhere), but it could be doing something funky in the script.

**Comment by bandgeekdante** [comment] 2019-10-14 15:16
It did indeed crop up again today. I didn't get any "no such table: solar" messages today, though I got:
```
10/14/19 09:06:27 darkmode: Failed conversion of ``'' using format ``%Y-%m-%d %H:%M:%S %z''
10/14/19 09:06:27 darkmode: date: illegal time format
10/14/19 09:06:27 darkmode: usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
10/14/19 09:06:27 darkmode:             [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
10/14/19 09:06:27 darkmode: Failed conversion of ``'' using format ``%Y-%m-%d %H:%M:%S %z''
10/14/19 09:06:27 darkmode: date: illegal time format
10/14/19 09:06:28 darkmode: usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
10/14/19 09:06:28 darkmode:             [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
10/14/19 09:06:29 darkmode: Solar query stored - Sunrise:  Sunset: 
```
Is it worth it to remove the log function? Wouldn't that mean I can no longer see these issues when they come up in the log?

**Comment by katernet** [comment] 2019-10-15 08:50
Just going back to krema's [comment](https://github.com/katernet/darkmode/issues/10#issuecomment-427643208) are you sure that in System Preferences the option Setting timezone using location is enabled in Date & Time > Timezone and Setting timezone is enabled in Security > Location Services > System Services? I just realised you hadn't confirmed that.

If so, as per my comments on Sep 13 this may be an issue with location settings on your system, as you can see in this [thread](https://github.com/JohnCoates/Aerial/issues/528).

If these don't work then I found the following which may help:
https://apple.stackexchange.com/questions/204874/osx-automatic-time-zone-detects-location-but-doesnt-update
https://apple.stackexchange.com/questions/16424/set-time-zone-automatically-using-current-location-is-not-working-why

I found this [gist](https://gist.github.com/grahamgilbert/4f203157a7463ee602493216871ac370) which enables the Setting timezone automatically option, however it requires root privileges, so that's out of the question, and I think SIP permits unloading of System launch daemons ...nope.

> Is it worth it to remove the log function? Wouldn't that mean I can no longer see these issues when they come up in the log?

Probably not. Yes this will prevent the logging of the issue. Just something I thought of while debugging.

Some quick and dirty code I may add to the `solar` function to introduce an easier to understand error log:

```diff
@@ -105,6 +105,9 @@
 	riseT=$(/usr/"$parentDir"/corebrightnessdiag nightshift-internal | grep nextSunrise | cut -d \" -f2)
 	setT=$(/usr/"$parentDir"/corebrightnessdiag nightshift-internal | grep nextSunset | cut -d \" -f2)
+	
+	if [[ -z $riseT || -z $setT ]]; then
+          return # Night shift output is empty, stop function.
+          echo "Night shift solar data is empty." | tee -a ~/Library/Logs/io.github.katernet.darkmode.log 1> /dev/null
+     fi
+	
 	# Test for 12 hour format
 	if [[ $riseT == *M* ]] || [[ $setT == *M* ]]; then
 		formatT="%Y-%m-%d %H:%M:%S %p %z"
```

**Comment by bandgeekdante** [comment] 2019-10-22 21:24
Hi katernet, thanks for all the help with this throughout the past year. Since upgrading to OS Catalina I'm now just going to use the auto dark mode feature.

**Comment by katernet** [comment] 2019-10-23 08:21
@bandgeekdante No problem man. Yes I updated the README when Catalina launched, to basically say there's no point in using this 😝

Sorry we couldn't get to the bottom of it. Good to chat with you.

**Closed as completed by katernet** 2019-10-23 08:21 UTC
Labels: bug
